In [4]:

import numpy as np 


In [5]:
a = np.array([[0,1,2,3], [10, 11, 12, 13]])

In [6]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [7]:
a.shape     # 2 rows, 4 in each row

(2, 4)

In [8]:
a.size   # total no of elements

8

In [9]:
a[1,3]     # row 2, element 4

13

In [10]:
a[1,3] = -1     # set element
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [11]:
a[1]    # = show second row


array([10, 11, 12, -1])

In [12]:
a[0, 1:3]    #slicing

array([1, 2])

In [22]:
b = np.array(range(1,37))
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [24]:
b.resize(6,6)
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [26]:
b[4:, 4:]

array([[29, 30],
       [35, 36]])

In [27]:
b[2::2, ::2]

array([[13, 15, 17],
       [25, 27, 29]])

In [29]:
b[:, 2]   # a specific column

array([ 3,  9, 15, 21, 27, 33])