In [ ]:

import numpy as np 


In [1]:
import numpy as np

## Data: yearly salary in ($1000) [2017, 2018, 2019]
alice = [99, 101, 103]
bob = [110, 108, 105]
tim = [90, 88, 85]

salaries = np.array([alice, bob, tim])
taxation = np.array([[0.2, 0.25, 0.22],
                     [0.4, 0.5, 0.5],
                     [0.1, 0.2, 0.1]])
#Problem: how do we find the maximum after-tax income in a group of people, #given their yearly salary and tax rates?

#solution:
max_income = np.max(salaries - salaries * taxation)
print(max_income)

81.0


In [ ]:
## Data: yearly salary in ($1000) [2025, 2026, 2027]
dataScientist = [130, 132, 137]
productManager = [127, 140, 145]
designer = [118, 118, 127]
softwareEngineer = [129, 131, 137]

employees = np.array([dataScientist,
                      productManager,
                      designer,
                      softwareEngineer])
#Problem: You have data for a variety of professions, and you want to increase the salaries of just the data scientists by 10 percent every other year.

#solution:
employees[0, ::2] = employees[0, ::2] * 1.10
print(employees)

In [2]:
## Dependencies
import numpy as np

## Data: air quality index AQI data (row = city)
X = np.array(
    [[ 42, 40, 41, 43, 44, 43 ], # Hong Kong
     [ 30, 31, 29, 29, 29, 30 ], # New York
     [ 8, 13, 31, 11, 11, 9 ], # Berlin
     [ 11, 11, 12, 13, 11, 12 ]]) # Montreal

cities = np.array(["Hong Kong", 
                   "New York", 
                   "Berlin", 
                   "Montreal"])
#Problem: find above-average polluted city names from a 2D matrix where each row maintains a city's AQI measurements. The one-liner finds above-average polluted cities, defined as cities that have a peak AQI value that is above the overall average among all the measurements of all cities.
# A common use for nonzero is to find the indices of an array, where a condition is True. Given an array a, the condition a > 3 is a boolean array and since False is interpreted as 0, np.nonzero(a > 3) yields the indices of the a where the condition is true.
avg = np.average(X)
print(avg)
print(cities[np.nonzero(X > np.average(X))[0]])
print(set(cities[np.nonzero(X > np.average(X))[0]]))

24.333333333333332
['Hong Kong' 'Hong Kong' 'Hong Kong' 'Hong Kong' 'Hong Kong' 'Hong Kong'
 'New York' 'New York' 'New York' 'New York' 'New York' 'New York'
 'Berlin']
{'Berlin', 'Hong Kong', 'New York'}


In [4]:
polluted = set(cities[np.nonzero(X > np.average(X))[0]])

In [5]:
print(polluted)

{'Berlin', 'Hong Kong', 'New York'}


In [20]:
#Problem: Given a 2D array (first column = # followers, second column = Instagram name). Find the names of the Instagram superstars with more than 100 million followers!
import numpy as np

## Data: popular Instagram accounts (millions followers)
inst = np.array([[232, "@instagram"],
                 [133, "@selenagomez"],
                 [59, "@victoriassecret"],
                 [120, "@cristiano"],
                 [111, "@beyonce"],
                 [76, "@nike"]])
more_100 = inst[inst[:, 0].astype(int) > 100, 1]   # 1= the column to show
print(more_100)
more_100 = inst[inst[:, 0].astype(int) > 100]
print(more_100)

['@instagram' '@selenagomez' '@cristiano' '@beyonce']
[['232' '@instagram']
 ['133' '@selenagomez']
 ['120' '@cristiano']
 ['111' '@beyonce']]


In [36]:
#Problem: Given an array of temperature values, replace every seventh temperature value with the average of the last seven days (including the seventh day’s temperature value).
## Dependencies
import numpy as np

## Sensor data (Mo, Tu, We, Th, Fr, Sa, Su)
tmp = np.array([1, 2, 3, 4, 3, 4, 4,
                5, 3, 3, 4, 3, 4, 6,
                6, 5, 5, 5, 4, 5, 5]).astype(float)
tmp2 = tmp.reshape((-1,7))
print(tmp2)
tmp[6::7] = np.average(tmp.reshape((-1,7)), axis=1)  # (-1)= computer calculate the number of elements for 7 columns (=3). only for the calculation sake.
print(tmp)


[[1. 2. 3. 4. 3. 4. 4.]
 [5. 3. 3. 4. 3. 4. 6.]
 [6. 5. 5. 5. 4. 5. 5.]]
[1. 2. 3. 4. 3. 4. 3. 5. 3. 3. 4. 3. 4. 4. 6. 5. 5. 5. 4. 5. 5.]
